---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, options(readr.show_col_types = FALSE))
```

# Stratification by nest and sex

```{r}
library(tidyverse)
library(ampir)
library(patchwork)
source("scripts/read_blast.R")
source("scripts/calculate_rpk_fold_change.R")
source("scripts/calculate_moving_sum.R")
source("scripts/ms_plot_clean.R")
source("scripts/read_ev_polyprotein_uniprot_metadata.R")
source("scripts/plot_ev_polyprotein.R")
```

Read in Cohort datasets generated in `01_figure_01_CXVB_antigen_mapping.Rmd`

```{r}
endia_virscan_onset <- read_rds("cache/endia_virscan_metadata.rds") %>% 
  filter(onset_visit == 1)

ENDIA_blastp_evB1 <- read_blast("raw_data/blast_results/blastp_endia_evB1_all_virscan_peps.blast")


vigr_virscan_metadata <- read_rds("cache/vigr_virscan_metadata.rds")

VIGR_blastp_evB1 <- read_blast("raw_data/blast_results/blastp_vigr_evB1_all_virscan_peps.blast")
```

Read in polyprotein metadata and plot
```{r}
coxsackievirusB1_P08291 <- read_ev_polyprotein_uniprot_metadata("raw_data/coxsackievirusB1_P08291.tsv")

EV_B1_plot <- plot_ev_polyprotein(coxsackievirusB1_P08291)
```

## Stratify by nest

### VIGR

```{r}
vigr_virscan_metadata <- vigr_virscan_metadata %>% mutate(Nest = str_extract(sample_id, "\\d+"))

VIGR_signal_per_nest_plots <- vigr_virscan_metadata %>%
  group_by(Nest) %>%
  arrange(Age) %>%
  group_map(~ .x %>%
    calculate_rpk_fold_change(sample_id, Condition, pep_id, abundance, VIGR_blastp_evB1) %>%
    calculate_moving_sum(value_column = fold_change, win_size = 32, step_size = 4) %>%
    ms_plot_clean() + 
      ggtitle(paste("Nest", unique(.x$Nest), "- Age", unique(.x$Age))) +
      theme(
        plot.title = element_text(size = 10) 
      ),
    .keep = TRUE
  )
```


```{r, echo = FALSE, fig.height=10, fig.width=10}
wrap_plots(VIGR_signal_per_nest_plots, ncol = 3)
```

### ENDIA

Filter to keep only nests that have Cases and Controls.
```{r}
endia_virscan_onset_complete_nests <- endia_virscan_onset %>% 
  group_by(deidentified_nest_id_new) %>%
  filter(all(c("Case", "Control") %in% condition)) %>%
  ungroup()
```

```{r}
ENDIA_signal_per_nest_plots <- endia_virscan_onset_complete_nests %>%
  group_by(deidentified_nest_id_new) %>%
  mutate(age_years = round(age_at_sample_collection_days / 365), digits = 1) %>% 
  group_map(~ .x %>%
    calculate_rpk_fold_change(sample_id, condition, pep_id, abundance, ENDIA_blastp_evB1) %>%
    calculate_moving_sum(value_column = fold_change, win_size = 32, step_size = 4) %>%
    ms_plot_clean() + 
      ggtitle(paste("Nest", unique(.x$deidentified_nest_id_new), "- Age", unique(.x$age_years))) +
      theme(
        plot.title = element_text(size = 10)
      ),
    .keep = TRUE
  )
```


```{r, echo = FALSE, fig.width=14, fig.height=9}
wrap_plots(ENDIA_signal_per_nest_plots, ncol = 6)
```


## Sex stratification in both cohorts

```{r}
endia_sex_stratified <- endia_virscan_onset_complete_nests %>%
  group_by(infant_sex) %>% 
  group_map(~ .x %>%
    calculate_rpk_fold_change(sample_id, condition, pep_id, abundance, ENDIA_blastp_evB1) %>%
    calculate_moving_sum(fold_change, 32, 4) %>%
    ms_plot_clean() + 
      ggtitle(paste("Sex:", unique(.x$infant_sex), "- Sample count:", length(unique(.x$sample_id)))) +
      theme(
        plot.title = element_text(size = 10)
      ),
    .keep = TRUE
  )

vigr_sex_stratified <- vigr_virscan_metadata %>%
  group_by(Sex) %>% 
  group_map(~ .x %>%
    calculate_rpk_fold_change(sample_id, Condition, pep_id, abundance, VIGR_blastp_evB1) %>%
    calculate_moving_sum(fold_change, 32, 4) %>%
    ms_plot_clean() + 
      ggtitle(paste("Sex:", unique(.x$Sex), "- Sample count:", length(unique(.x$sample_id)))) +
      theme(
        plot.title = element_text(size = 10)
      ),
    .keep = TRUE
  )

vigr_sex_plots <- wrap_plots(EV_B1_plot + ggtitle("VIGR"), wrap_plots(vigr_sex_stratified, ncol = 1) +
             labs(x = "Position in sequence (amino acids)")  + theme(legend.position = "bottom"), ncol = 1, heights = c(0.3, 3)) &
  theme(plot.margin = margin(5.5, 5.5, 5.5, 0))

endia_sex_plots <- wrap_plots(EV_B1_plot + ggtitle("ENDIA"), wrap_plots(endia_sex_stratified, ncol = 1) +
             labs(x = "Position in sequence (amino acids)") + theme(legend.position = "bottom"), ncol = 1, heights = c(0.3, 3)) 

cohorts_sex_plot <- wrap_plots(vigr_sex_plots, endia_sex_plots)

cohorts_sex_plot_with_yaxis <- wrap_elements(cohorts_sex_plot) +
  labs(tag = expression(sum((bar(X)[rpk_cases] - bar(X)[rpk_controls])))) +
  theme(
    plot.tag = element_text(size = rel(1), angle = 90),
    plot.tag.position = "left")
```


```{r, fig.height=8, fig.width=17, echo = FALSE}
cohorts_sex_plot_with_yaxis
```

```{r, echo = FALSE}
ggsave("figures/cohorts_sex_plot.png", plot = cohorts_sex_plot_with_yaxis, width = 17, height = 6, dpi = 300)
ggsave("figures/cohorts_sex_plot.svg", plot = cohorts_sex_plot_with_yaxis, width = 17, height = 6, dpi = 300)
```

