---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Motif enrichment on ENDIA with 1:1 ratio

```{r}
library(tidyverse)
source("scripts/read_blast.R")
library(glmmTMB)
```

Read in ENDIA metadata with participants matched to a 1:1 ratio across the nests.
Created in `obtaining_1to1_nest_ratio.Rmd`
```{r}
endia_metadata_1to1 <- read_rds("cache/endia_matched_1to1.rds")
```

```{r}
endia_metadata_1to1 %>% 
  distinct(participant_id, .keep_all = TRUE) %>% 
  group_by(deidentified_nest_id_new) %>%
  summarise(
    cases = sum(condition == "Case"),
    controls = sum(condition == "Control")) %>% 
    mutate(case_control_ratio = paste(cases, controls, sep = ":")) %>% 
   count(case_control_ratio, name = "number of nests")
```

```{r}
endia_virscan_hits_counts_annot1_3 <- read_tsv("raw_data/virscan_hits_counts/phip11_plate1-3_v_kiwook_2_CDIVirScan_000_Hits_counts_annotated.tsv") %>% 
  select(-contains("Beads_Only")) %>% 
  pivot_longer(cols = starts_with("KiWook"), names_to = "participant_id", values_to = "abundance") 

endia_virscan_hits_counts_annot4_6 <- read_tsv("raw_data/virscan_hits_counts/phip11_plate4-6_v_kiwook_2_CDIVirScan_000_Hits_counts_annotated.tsv") %>% 
   select(-contains("Beads_Only"),
          -KiWook_PhIP11_Plate6_81_G9_POWH_SAMPLE) %>% #remove positive control 
  pivot_longer(cols = starts_with("KiWook"), names_to = "participant_id", values_to = "abundance")

endia_virscan_long <- bind_rows(endia_virscan_hits_counts_annot1_3, endia_virscan_hits_counts_annot4_6) %>% 
  group_by(pep_id) %>%
  filter(any(abundance > 0)) %>% # remove peptides that are 0 in all samples
  ungroup() %>% 
  group_by(participant_id) %>% 
  filter(sum(abundance) != 0) %>% # remove samples with 0 peptides detected 
  ungroup() %>% 
  mutate(sample_id = str_remove(participant_id, "^(?:[^_]+_){5}"),   # keep everything after the 5th _
          timepoint = str_extract(sample_id, "[^_]+$"),           # extract last segment from sample_id
          participant_id = str_remove(sample_id, "_[^_]+$"),        # remove timepoint from sample_id
          .keep = "unused")

endia_virscan_metadata <- endia_virscan_long %>% 
  left_join(endia_metadata_1to1, by = join_by(sample_id, participant_id)) 
```

```{r}
endia_virscan_onset1to1 <- endia_virscan_metadata %>% 
  filter(onset_visit == 1) %>% 
  group_by(sample_id) %>% 
  mutate(rpk = abundance / sum(abundance) * 100000) %>% 
  mutate(log_lib = log(sum(abundance) + 1e-8)) %>% # add offset for testing 
  ungroup()
```


```{r}
endia_blastp_ev_motifs <- read_blast("raw_data/blast_results/blastp_endia_ev_motifs.blast")

endia_motif_results1to1 <- endia_blastp_ev_motifs %>%
    left_join(endia_virscan_onset1to1, by = join_by(qaccver == pep_id)) 

endia_motif_for_stats1to1 <- endia_motif_results1to1 %>% 
  filter(taxon_genus == "Enterovirus") %>% 
  group_by(saccver, sample_id) %>% 
  mutate(total_rpk = sum(rpk)) %>% 
  mutate(total_abundance = sum(abundance)) %>% 
  ungroup() %>% 
  select(saccver, sample_id, case, condition, taxon_genus, total_rpk, infant_id, mother_id, 
         deidentified_nest_id_new, age_at_sample_collection_days, infant_sex,
         infant_HLA, weightTEDDY, maternal_T1D, total_abundance, log_lib) %>% 
  distinct(saccver, taxon_genus, sample_id, .keep_all = TRUE) %>% 
  mutate(age_sample_collection_month = age_at_sample_collection_days / 365 * 12) %>% 
  mutate(log_total_rpk = log(total_rpk + 1)) %>% 
  mutate(across(c(infant_HLA, maternal_T1D, infant_id, mother_id, deidentified_nest_id_new, infant_sex), as.factor)) %>% 
  mutate(age_c = scale(age_at_sample_collection_days)) %>% 
  mutate(total_rpk_int = as.integer(total_rpk)) %>%  # also testing
  mutate(Condition = factor(condition, levels = c("Control", "Case"), labels = c("Control", "Case"))) # for testing purposes
```

ENDIA 3D region 

```{r}
endia_3d_motif_for_stats1to1 <- endia_motif_for_stats1to1 %>% filter(saccver == "3D_motif")

endia_3d_model1to1 <- glmmTMB(formula = case ~ log_total_rpk + infant_HLA + age_sample_collection_month + infant_sex + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_3d_motif_for_stats)

endia_3d_model1to1 %>% broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE)

summary(endia_3d_model1to1)
```

```{r}
endia_3d_motif_for_stats_xy1to1 <- endia_motif_for_stats1to1 %>% filter(infant_sex == "Male")
endia_3d_motif_for_stats_xx1to1 <- endia_motif_for_stats1to1 %>% filter(infant_sex == "Female")

endia_3d_model_xy1to1 <- glmmTMB(formula = case ~ log_total_rpk + infant_HLA + age_sample_collection_month + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_3d_motif_for_stats_xy1to1)

endia_3d_model_xx1to1 <- glmmTMB(formula = case ~ log_total_rpk + infant_HLA + age_sample_collection_month + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_3d_motif_for_stats_xx1to1)

endia_3d_model_xy1to1 %>% broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) 

endia_3d_model_xx1to1 %>% broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) 

summary(endia_3d_model_xy1to1)
```

### VP1 

```{r}
endia_vp1_motif_for_stats1to1 <- endia_motif_for_stats1to1 %>% filter(saccver == "VP1_motif")

endia_vp1_model1to1 <- glmmTMB(formula = case ~ log_total_rpk + infant_HLA + age_sample_collection_month + infant_sex + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_vp1_motif_for_stats1to1)

endia_vp1_model1to1 %>% broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) 

summary(endia_vp1_model1to1)

glmmTMB(formula = case ~ log_total_rpk * infant_sex + infant_HLA + age_sample_collection_month + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_vp1_motif_for_stats1to1) %>% 
  summary()
```

Separate sexes 

```{r}
endia_vp1_motif_for_stats_xy1to1 <- endia_vp1_motif_for_stats1to1 %>% filter(infant_sex == "Male")
endia_vp1_motif_for_stats_xx1to1 <- endia_vp1_motif_for_stats1to1 %>% filter(infant_sex == "Female")


endia_vp1_xy_model1to1 <- glmmTMB(formula = case ~ log_total_rpk + infant_HLA + age_sample_collection_month + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_vp1_motif_for_stats_xy1to1)

endia_vp1_xx_model1to1 <- glmmTMB(formula = case ~ log_total_rpk + infant_HLA + age_sample_collection_month + maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_vp1_motif_for_stats_xx1to1)

endia_vp1_xx_model1to1 %>% broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) 

endia_vp1_xy_model1to1 %>% broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) 

summary(endia_vp1_xy_model1to1)
summary(endia_vp1_xx_model1to1)
```

results for males VP1
```{r}
endia_vp1_xy_model1to1 %>%
  broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) %>% 
  mutate(conf_low_int = as.integer(conf.low),
         conf_high_int = as.integer(conf.high)) %>% 
  select(term, p.value, conf_low_int, conf_high_int, conf.low, conf.high)

```

trying with offset for poisson , doesn't work well
```{r}
glmmTMB(formula = case ~ log(total_abundance) + infant_HLA + age_sample_collection_month + maternal_T1D + offset(log_lib) +  (1|mother_id),
       family = poisson(link = "log"),
       data = endia_vp1_motif_for_stats_xy1to1)

glmmTMB(formula = total_abundance ~ Condition + infant_HLA + age_sample_collection_month + offset(log_lib) +  maternal_T1D + (1|mother_id),
       family = poisson(link = "log"),
       data = endia_vp1_motif_for_stats_xy1to1)
```


trying with binomial, with and without offset
```{r}
endia_vp1_xy_model1to1_binomial_offset <- glmmTMB(formula = Condition ~ total_abundance + infant_HLA + age_sample_collection_month + maternal_T1D + offset(log_lib) + (1|mother_id),
       family = binomial(link = "logit"),
       data = endia_vp1_motif_for_stats_xy1to1)

endia_vp1_xy_model1to1_binomial <- glmmTMB(formula = Condition ~ log_total_rpk + infant_HLA + age_sample_collection_month + maternal_T1D + (1|mother_id),
       family = binomial(link = "logit"),
       data = endia_vp1_motif_for_stats_xy1to1)

anova(endia_vp1_xy_model1to1, endia_vp1_xy_model1to1_binomial_offset,endia_vp1_xy_model1to1_binomial )

```

binomial tests 
```{r}
endia_vp1_xy_model1to1_binomial_offset %>%
  broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) %>% 
  mutate(conf_low_int = as.integer(conf.low),
         conf_high_int = as.integer(conf.high)) %>% 
  select(term,p.value, conf_low_int, conf_high_int, conf.low, conf.high)


endia_vp1_xy_model1to1_binomial %>%
  broom.mixed::tidy(conf.int = TRUE, exponentiate = TRUE) %>% 
  mutate(conf_low_int = as.integer(conf.low),
         conf_high_int = as.integer(conf.high)) %>% 
  select(term, p.value, conf_low_int, conf_high_int, conf.low, conf.high)
```




